version: "3.9"
services:
   minio:
     image: quay.io/minio/minio
     command: server /data --console-address ":9001"
     environment:
        MINIO_ROOT_USER: admin@parnter
        MINIO_ROOT_PASSWORD: partner@2564
     volumes:
       - ./minio/data:/data
     ports:
      - "9000:9000"
      - "9001:9001"