name: CI/CD Pipeline
concurrency: korat-x-tech-project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: korat-x-tech-project
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: "check echo"  
      run: |
        echo "Hello World"
  