name: CD Pipeline
concurrency: korat-x-tech-project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: korat-x-tech-project
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: "check ls"  
      run: |
        ls -la

    - name: Build and push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 
        docker build -t nitikornchumnankul/korat-x-tech-project:v1.0.${{ github.run_number }} ./korat-x-tech-project
        docker push nitikornchumnankul/korat-x-tech-project:v1.0.${{ github.run_number }}
    - name: SSH to VM and deploy
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          export version=v1.0.${{ github.run_number }}
          docker compose up -d
  